version: "2"
linters:
  default: none
  enable:
    - errorlint
    - ineffassign
    - revive
    - staticcheck
  settings:
    errorlint:
      errorf: true
      asserts: false
      comparison: false
    staticcheck:
      checks:
        - -SA1019
        - -ST1003
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: don't use underscores
      - linters:
          - revive
        text: don't use ALL_CAPS
      - linters:
          - revive
        text: stutter
      - linters:
          - revive
        text: unexported-return
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - revive
        text: superfluous-else
      - linters:
          - revive
        text: empty-block
    paths:
      - pkg/uroot/test
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
