---
name: TinyGo regression test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: tinygo/tinygo-dev:sha-0426a5f90247b29a8960702e680b23b66f3af17d
    steps:
      - name: Install actions dependencies into tinygo container (Debain)
        run: |
          apt-get update
          apt-get install -y nodejs
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - name: Run regression builder
        run: |
          # the docker image adds tinygo to the path
          TINYGO=$(which tinygo)
          TINYGOVER=$($TINYGO version | awk {'print $3'})
          GOVER=$(go version | awk {'print $3'} )

          go run tools/regression/main.go \
              -tinygo $TINYGO \
              -commit-tinygo $TINYGOVER \
              -commit-uroot $(git rev-parse HEAD) \
              -version-go $GOVER \
              cmds/core/* cmds/exp/* > $GITHUB_STEP_SUMMARY